### ISSUE TITLE
About the command

### ISSUE THREAD

**Issue by alfredcc** [nixzhu/Coolie#1]
Awesome. Thank you nixzhou.

```
$ xcrun swiftc Sources/*.swift -o coolie
$ ./coolie test.son User
```

Above command line need alias the `xcrun` line by putting this line in your .bash_profile first
`alias swiftc='xcrun -sdk macosx swift'`

**Comment by tschoffelen** [comment]
Or just adding `-sdk macosx` to the `xcrun` command also works:

```
$ xcrun -sdk macosx swiftc Sources/*.swift -o coolie
$ ./coolie testj.son User
```
