### ISSUE TITLE
Invalid characters in generated Swift structs

### ISSUE THREAD

**Issue by thebradbain** [nixzhu/Coolie#5]
Awesome project! 

One thing I noticed (if only because it affected me): if a JSON key has a character that is unable to be within a Swift variable, such as "/", the generated Swift code does not account for it.

**E.G.**

```
{ "some_variable/_text" : "hello, world" }  
```

becomes

```
let someVariable/Text: String
```

which is invalid

**Comment by nixzhu** [comment]
Thanks! Latest code fixed invalid property name.
Coolie may not generate perfect code, it do the nasty work for you, then you modify the models.
