### ISSUE TITLE
发现一个问题

### ISSUE THREAD

**Issue by Gilbertat** [nixzhu/Coolie#6]
类似于这样的json
`{
  "error": "",
  "count": 10,
  "posts": [
    {
      "id": "1853",
      "date": "2016-02-18",
      "name": "archive",
      "pic": "http://www.kanzhihu.com/wp-content/uploads/2016/02/archive-2016-02-18.jpg",
      "publishtime": "1455786000",
      "count": "32",
      "excerpt": "摘录了『人这一生为什么要努力？』、『日本究竟发达到什么程度？』、『野球场上，你见过最装逼的是什么？』、『什么是 Vim 可以做而 Emacs 做不到的？』、『吃过最好吃的东西是什么？』、『文案的价值在哪里？为什么凭几句广告语就能拿那么多工资？』、『27岁女生，单身，无学历无背景，现在感到很迷茫？』、『如果炉石传说里的随从或职业玩知乎，他们会提什么问题？』、『你遇过的最温暖的瞬间是什么？』、『为什么要使用 Go 语言？Go 语言的优势在哪里？』等问题下的32个答案"
    },
{
      "id": "1844",
      "date": "2016-02-15",
      "name": "archive",
      "pic": "http://www.kanzhihu.com/wp-content/uploads/2016/02/archive-2016-02-15.jpg",
      "publishtime": "1455526800",
      "count": "32",
      "excerpt": "摘录了『有哪些物美价廉的淘宝店值得推荐？』、『北欧究竟发达到什么程度?』、『外蒙古地区独立对我国是利大于弊还是弊大于利？』、『怎样可以像法国女人一样优雅？』、『你家猫最逗比的时刻是什么时刻？』、『你是怎样通过学习改变命运的？』、『给认识不久的妹子准备一个什么圣诞礼物比较合适?』、『有哪些著名的「我秃了，也变强了」的人物？』、『什么样的讲话算「有水平」？』、『你见过最丑的设计是什么？』、『作为 Airbnb 房东，你对自己出租的空间有哪些装点心得？』等问题下的32个答案"
    }
  ]
}`
使用命令 ./coolie zhihu.json User
会出现错误
`Not found valid token
fatal error: Array index out of range
[1]    21517 illegal hardware instruction  ./coolie zhihu.json Users`

**Comment by Gilbertat** [comment]
使用最新的则会报错
not found valid token
No token for parseString
Expect key : value
Parse failed!

**Comment by nixzhu** [comment]
Thanks! Fixed in latest code. The reason is the value of "error" is a empty string.
