### ISSUE TITLE
can't build

### ISSUE THREAD

**Issue by zhouzizi** [nixzhu/Coolie#9]
xcrun: error: active developer path ("/Applications/Xcode-beta.app/Contents/Developer") does not exist, use `xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools (or see `man xcode-select`)

**Comment by nixzhu** [comment]
Do not use Xcode beta or do as the error says.

**Comment by zhouzizi** [comment]
![f8dc3790-82a8-4a6c-9dc3-dab942535a8b](https://cloud.githubusercontent.com/assets/9103749/15311054/7f7dfad0-1c29-11e6-81ff-b507e2bd197e.png)
![aa59c583-36bf-49a0-a142-a0abe5941c8d](https://cloud.githubusercontent.com/assets/9103749/15311060/89acf204-1c29-11e6-9a96-c24331dd2fe9.png)
![c2295f02-9599-45c8-805f-4d463e845575](https://cloud.githubusercontent.com/assets/9103749/15311070/9cc4eb4e-1c29-11e6-8aa5-7e6a2fd1d372.png)

**Comment by nixzhu** [comment]
Coolie now with new command usage. You need to read README (again).

**Comment by zhouzizi** [comment]
![image](https://cloud.githubusercontent.com/assets/9103749/15311220/2e591138-1c2b-11e6-9bb1-c0e30d14438e.png)

**Comment by nixzhu** [comment]
You input `—model-roomid`? That’s not a valid option, try read & see words.

PS: I don’t like you just post an screenshot, before you disturb anyone, make sure it’s not your mistake.

**Comment by zhouzizi** [comment]
```
./coolie -i test.json --model-name User
```

name is not an argument...
thanks a lot !
